name: marvel
description: Marvel app FIAP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  crypto: ^3.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  formz: ^0.4.1
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  http: ^0.13.4
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/graphics/images/
    - assets/graphics/gifs/